# Generated by Django 4.1.5 on 2023-01-16 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0002_alter_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_discuss',
            new_name='discussion_id',
        ),
    ]
